version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: "UK Smoke tests"
          executor: cypress/browsers-chrome77
          browser: chrome
          store_artifacts: true
          spec: "*/**/smokeTest-UK.spec.js"
      - cypress/run:
          name: "XI Smoke tests"
          executor: cypress/browsers-chrome77
          browser: chrome
          store_artifacts: true
          spec: "*/**/smokeTest-XI.spec.js"
