version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: "UK Smoke tests"
          executor: cypress/browsers-chrome77
          browser: chrome
          store_artifacts: true
          spec: "*/**/smokeTest-UK.spec.js"
          post-steps:
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: mochawesome-report
      - cypress/run:
          name: "XI Smoke tests"
          executor: cypress/browsers-chrome77
          browser: chrome
          store_artifacts: true
          spec: "*/**/smokeTest-XI.spec.js"
          post-steps:
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: mochawesome-report
