version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
  slack: circleci/slack@4.1

workflows:
  build:
    jobs:
      - cypress/run:
          name: "UK Smoke tests"
          executor: cypress/browsers-chrome77
          browser: chrome
          store_artifacts: true
          spec: "*/**/smokeTest-UK.spec.js"
          post-steps:
            - run: mkdir -p cypress/reports/mochareports
            - run: npm run combine-reports && npm run generate-report
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/reports
            - slack/notify:
                channel: tariffs-etl
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "plain_text",
                            "text": "*UK Report*",
                            "emoji": true
                          }
                        ]
                      }
                    ]
                  }
                event: always

      - cypress/run:
          name: "XI Smoke tests"
          executor: cypress/browsers-chrome77
          browser: chrome
          store_artifacts: true
          spec: "*/**/smokeTest-XI.spec.js"
          post-steps:
            - run: mkdir -p cypress/reports/mochareports
            - run: npm run combine-reports && npm run generate-report
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/reports
            - slack/notify:
                channel: tariffs-etl
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "plain_text",
                            "text": "*XI Report*",
                            "emoji": true
                          }
                        ]
                      }
                    ]
                  }
                event: always
