name: "Reports"
on: [push]
#on:
#  schedule:
#    - cron:  '0 * * * *'
jobs:
  cypress-run:
    name: Scheduled hourly run
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p cypress/reports/mochareports
      - uses: cypress-io/github-action@v2
        with:
          quiet: false
          browser: chrome
          headless: true
          spec: "*/**/smokeTest-XI.spec.js,*/**/smokeTest-NUK.spec.js"
      - run: npm run posttests
      - run: ls -l
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./cypress/reports/mochareports/
      - run: |
          DATE=$(date +%m-%d-%Y)
          mkdir -p docs/$DATE
          cp -r ./cypress/reports/mochareports/*  docs/$DATE/
          cp ./cypress/reports/mochareports/report.html docs/$DATE/index.html
          git add docs .
      - run: |
          git config --local user.email "tradetarrif+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: reports
          force: true
