name: "Reports"
#on: [workflow_dispatch]
on: [push]
jobs:
  cypress-run:
    name: Reporting test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - run: env
      - run: echo $GITHUB_TOKEN
      - uses: cypress-io/github-action@v2
        with:
          quiet: false
          browser: chrome
          headless: true
          spec: "*/**/smokeTest-XI.spec.js,*/**/smokeTest-NUK.spec.js"
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: mochawesome-report/
          if-no-files-found: error
